### ISSUE TITLE
is_english_char函数问题，字典问题

### ISSUE THREAD

**Issue by brealisty** [shibing624/companynameparser#1]
### Describe the Question
测试了几个demo，粗略的看了一下代码和字典文件。其中parser.py中is_english_char函数的逻辑是判断否是是英文字母吗？如果是的话，这里149行的代码逻辑是否有误？
了解了一下企业名称命名规则，公司名后缀（组织形式，eg：有限公司），其中包括”中心“、”部“、”厂“、”店“等，但是在字典文件brand.txt中，又部分“xx厂”的词汇，这么设计是出于什么考量呢？

### Describe your attempts
- [X] I walked through the tutorials
- [X] I checked the documentation
- [X] I checked to make sure that this is not a duplicate question

**Comment by shibing624** [comment]
1. fixed. https://github.com/shibing624/companynameparser/commit/a0827831cb01b9005658c477cf4331d2f868724c

2. xx厂 之类的短词是按约定划分到brand的，公司名后缀适用的是正规的长公司名，短名称起名很灵活，如“门诊部、粮食局”代表的意思是单位本身，不适合再继续切分，故归类到brand，而brand为公司名的核心词。
